### ISSUE TITLE
curseforge mods always return "unknown slug"

### ISSUE THREAD

**Issue by LonelyMusicDisc** [Tom-The-Geek/pack-it#3]
```
pack-it curseforge-add cloth-config
ℹ️  Resolving cloth-config...
Error: unknown slug: cloth-config
```

even though cloth-config is an actual slug:
https://www.curseforge.com/minecraft/mc-mods/cloth-config/

**Comment by mdonoughe** [comment]
[NikkyAI/CurseProxy#6](https://github.com/NikkyAI/CurseProxy/issues/6)

**Comment by Tom-The-Geek** [comment]
Yeah, its also NikkyAI/CurseProxy#5. Not sure what to do about it apart from wait, this issue also seems to be affecting [packwiz](https://github.com/comp500/packwiz) too, but I don't think they have as many issues because you can add via addon/file id rather than just slug.

**Comment by Tom-The-Geek** [comment]
So I've started work on allowing adding mods by ID as well as slug on the [fix/invalid-slug](https://github.com/Tom-The-Geek/pack-it/tree/fix/invalid-slug) branch, but at the minute it still doesn't work because it looks up ID->slug then passes that via the (currently) broken system. I'll continue looking at this soon, but if anyone wants to PR and finish it off before I get the chance, then go ahead :).

**Comment by LonelyMusicDisc** [comment]
thank you for your work either way! love this program.

**Comment by RealityAnomaly** [comment]
Fixed by Fixed by https://github.com/NikkyAI/CurseProxy/pull/7
